### ISSUE TITLE
jQuery Dependency

### ISSUE THREAD

**Issue by brunowego** [FauzanKhan/angular-popover#1]
You have a nice job here, congrats! I see in your code functions from jQuery like `outerWidth` and `outerHeight`, you talk about remove jQuery dependency in the README file, how you will remove this dependencies?

**Comment by brunowego** [comment]
Perhaps creating a provider like this https://github.com/mgcrea/angular-jquery/blob/master/src/jquery.js

**Comment by FauzanKhan** [comment]
Hi @brunowego ,

Glad that you liked it. I plan on removing the dependency on jQuery by replacing the jQuery dependent code with equivalent vanilla JS code. I don't think it'll be too tedious to do. However, I'll see if I can leverage the provider you've mentioned above. Thanks for bringing it into my notice.

**Comment by brunowego** [comment]
Nice @FauzanKhan, thanks!
