### ISSUE TITLE
Hi there, very nice module, however, can u please add the unminified version of app.js to the repo?

### ISSUE THREAD

**Issue by paulpreibisch** [FauzanKhan/angular-popover#2]
Hi there, upon analysing your source code to learn how to use this module, I found that only the minified version of app.js has been included.

Can you kindly include the app.js version?  I think it will be helpful for those bootstrapping this module into their apps... thanks

**Comment by FauzanKhan** [comment]
Hi @paulpreibisch . I'm glad that the module is of any help to you. You can get the un-minified version of files in the `src` folder of the repo. [Click here](https://github.com/FauzanKhan/angular-popover/tree/master/src/js) to see the un-minified JS files.

**Comment by paulpreibisch** [comment]
ah thanks! I just found it!
