### ISSUE TITLE
Cannot read property 'addEventListener' of null

### ISSUE THREAD

**Issue by benjamindamm** [FauzanKhan/angular-popover#4]
How can I solve this problem?

**Comment by FauzanKhan** [comment]
Can you provide me any details to reproduce the issue?

**Comment by benjamindamm** [comment]
I injected ngPopoverFactory into my controller and in my root app module ngPopover, but I got the error "Cannot read property 'addEventListener' of null" in my console. More information isnt displayed.

**Comment by jmls** [comment]
did you ever get this fixed ? I've got exactly the same error

**Comment by jmls** [comment]
ha - and now I just fixed it ;) The sample

```
 <ng-popover trigger="popoverTrigger"
```

should read

```
 <ng-popover trigger="popover-trigger"
```

well - at least it stops the error ;)

**Comment by jmls** [comment]
ok, I found my problem - the trigger div was in a ng-repeat where I had no data to repeat:) Thus the dom wasn't being generated, and the id didn't exist

So, @benjamindamm , either you've done the same, or not named the id of the trigger div and the "trigger" attribute to be the same.

Try

```
<div id="popover" class="ng-popover-trigger">
    <h1>Open Popover</h1>
</div>

<ng-popover trigger="popover" direction="left" popover-class="custom-popover" on-open="$ctrl.openCallback()" on-close="$ctrl.closeCallback()">
                <h5>huzzahh</h5>
    </ng-popover>
```

**Comment by mhaefele** [comment]
Ah... I had the same issue.
I think the readme.md example might be incorrect.
trigger="popoverTrigger" in the ng-popover, but
id="popover-trigger"         // Notice the same ID is provided in the trigger attribute of the popover
in the trigger span ("popoverTrigger" vs "popover-trigger")

**Comment by FauzanKhan** [comment]
Hey guys, I had a typo in the `readme`. the `trigger` attribute of `ng-popover` and `id` of the trigger element need to have the same string. Thanks to @mhaefele & @jmls for pointing this out!
