### ISSUE TITLE
What's the license? 

### ISSUE THREAD

**Issue by fboucquez** [FauzanKhan/angular-popover#7]
Hi Fauzan, great job with this component. 

I would like to use this library in one of our products but that depends on the license. Is it MIT?

Could you add the license information to the source code?

For example, the LICENSE file in https://github.com/angular-translate/angular-translate

Cheers
Fernando

**Comment by FauzanKhan** [comment]
Hi @fboucquez 

Yes, the license is MIT, I've added the license information to the repository. Feel free to use and distribute it.
